services:
  app:
    image: ghcr.io/redstom/undercover-naruto:latest
    restart: unless-stopped
    environment:
      - NITRO_BUN_IDLE_TIMEOUT=60
      - APP_URL=https://undercover.vps.redstom.fr
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.undercover-naruto.rule=Host(`undercover-naruto.vps.redstom.fr`)"
      - "traefik.http.routers.undercover-naruto.entrypoints=websecure"
      - "traefik.http.routers.undercover-naruto.tls.certresolver=letsencrypt"
      - "traefik.http.services.undercover-naruto.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true